# coding: utf-8

"""
    ValStorm API

    Build better business with ValStorm APIs

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from valstorm_api.api.registration_api import RegistrationApi


class TestRegistrationApi(unittest.TestCase):
    """RegistrationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RegistrationApi()

    def tearDown(self) -> None:
        pass

    def test_activate_invite_v1_register_activate_invite_post(self) -> None:
        """Test case for activate_invite_v1_register_activate_invite_post

        Activate Invite
        """
        pass

    def test_activate_user_v1_register_activate_post(self) -> None:
        """Test case for activate_user_v1_register_activate_post

        Activate User
        """
        pass

    def test_register_user_to_org_v1_register_user_post(self) -> None:
        """Test case for register_user_to_org_v1_register_user_post

        Register User To Org
        """
        pass

    def test_register_user_v1_register_post(self) -> None:
        """Test case for register_user_v1_register_post

        Register User
        """
        pass


if __name__ == '__main__':
    unittest.main()
