# coding: utf-8

"""
    ValStorm API

    Build better business with ValStorm APIs

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from valstorm_api.models.send_grid_attachment import SendGridAttachment

class TestSendGridAttachment(unittest.TestCase):
    """SendGridAttachment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SendGridAttachment:
        """Test SendGridAttachment
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SendGridAttachment`
        """
        model = SendGridAttachment()
        if include_optional:
            return SendGridAttachment(
                file_content = '',
                file_name = '',
                file_type = '',
                disposition = ''
            )
        else:
            return SendGridAttachment(
                file_content = '',
                file_name = '',
        )
        """

    def testSendGridAttachment(self):
        """Test SendGridAttachment"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
