# coding: utf-8

"""
    ValStorm API

    Build better business with ValStorm APIs

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from valstorm_api.models.phone_address_type import PhoneAddressType

class TestPhoneAddressType(unittest.TestCase):
    """PhoneAddressType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPhoneAddressType(self):
        """Test PhoneAddressType"""
        # inst = PhoneAddressType()

if __name__ == '__main__':
    unittest.main()
