# coding: utf-8

"""
    ValStorm API

    Build better business with ValStorm APIs

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from valstorm_api.api.schema_api import SchemaApi


class TestSchemaApi(unittest.TestCase):
    """SchemaApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SchemaApi()

    def tearDown(self) -> None:
        pass

    def test_create_schema_field_v1_schema_field_post(self) -> None:
        """Test case for create_schema_field_v1_schema_field_post

        Create Schema Field
        """
        pass

    def test_create_schema_v1_schema_post(self) -> None:
        """Test case for create_schema_v1_schema_post

        Create Schema
        """
        pass

    def test_delete_schema_field_v1_schema_object_id_field_name_delete(self) -> None:
        """Test case for delete_schema_field_v1_schema_object_id_field_name_delete

        Delete Schema Field
        """
        pass

    def test_delete_schema_route_v1_schema_schema_id_delete(self) -> None:
        """Test case for delete_schema_route_v1_schema_schema_id_delete

        Delete Schema Route
        """
        pass

    def test_generate_schema_v1_schema_generate_post(self) -> None:
        """Test case for generate_schema_v1_schema_generate_post

        Generate Schema
        """
        pass

    def test_get_schema_v1_schema_object_get(self) -> None:
        """Test case for get_schema_v1_schema_object_get

        Get Schema
        """
        pass

    def test_get_schemas_v1_schemas_get(self) -> None:
        """Test case for get_schemas_v1_schemas_get

        Get Schemas
        """
        pass

    def test_update_schema_field_v1_schema_field_patch(self) -> None:
        """Test case for update_schema_field_v1_schema_field_patch

        Update Schema Field
        """
        pass

    def test_update_schema_v1_schema_patch(self) -> None:
        """Test case for update_schema_v1_schema_patch

        Update Schema
        """
        pass


if __name__ == '__main__':
    unittest.main()
