# coding: utf-8

"""
    ValStorm API

    Build better business with ValStorm APIs

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from valstorm_api.models.oauth_authorize_input import OauthAuthorizeInput

class TestOauthAuthorizeInput(unittest.TestCase):
    """OauthAuthorizeInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OauthAuthorizeInput:
        """Test OauthAuthorizeInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OauthAuthorizeInput`
        """
        model = OauthAuthorizeInput()
        if include_optional:
            return OauthAuthorizeInput(
                client_id = '',
                redirect_uri = '',
                response_type = '',
                state = '',
                scope = '',
                code_challenge = ''
            )
        else:
            return OauthAuthorizeInput(
                client_id = '',
                redirect_uri = '',
                response_type = '',
        )
        """

    def testOauthAuthorizeInput(self):
        """Test OauthAuthorizeInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
