# coding: utf-8

"""
    ValStorm API

    Build better business with ValStorm APIs

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from valstorm_api.api.apply_apps_api import ApplyAppsApi


class TestApplyAppsApi(unittest.TestCase):
    """ApplyAppsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ApplyAppsApi()

    def tearDown(self) -> None:
        pass

    def test_apply_apps_route_v1_apps_apply_apps_post(self) -> None:
        """Test case for apply_apps_route_v1_apps_apply_apps_post

        Apply Apps Route
        """
        pass


if __name__ == '__main__':
    unittest.main()
