# coding: utf-8

"""
    ValStorm API

    Build better business with ValStorm APIs

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from valstorm_api.api.search_admin_api import SearchAdminApi


class TestSearchAdminApi(unittest.TestCase):
    """SearchAdminApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SearchAdminApi()

    def tearDown(self) -> None:
        pass

    def test_check_opensearch_connection_v1_search_admin_connection_get(self) -> None:
        """Test case for check_opensearch_connection_v1_search_admin_connection_get

        Check OpenSearch Connection
        """
        pass

    def test_create_new_index_v1_search_admin_index_index_name_post(self) -> None:
        """Test case for create_new_index_v1_search_admin_index_index_name_post

        Create Index
        """
        pass

    def test_delete_existing_index_v1_search_admin_index_index_name_delete(self) -> None:
        """Test case for delete_existing_index_v1_search_admin_index_index_name_delete

        Delete Index
        """
        pass

    def test_flush_opensearch_database_v1_search_admin_flush_db_delete(self) -> None:
        """Test case for flush_opensearch_database_v1_search_admin_flush_db_delete

        Flush Application Indexes
        """
        pass

    def test_get_all_documents_in_index_v1_search_admin_index_index_name_documents_get(self) -> None:
        """Test case for get_all_documents_in_index_v1_search_admin_index_index_name_documents_get

        Get All Documents in Index
        """
        pass

    def test_get_index_info_v1_search_admin_index_index_name_get(self) -> None:
        """Test case for get_index_info_v1_search_admin_index_index_name_get

        Get Index Information
        """
        pass

    def test_list_all_system_opensearch_indexes_v1_search_admin_index_all_system_get(self) -> None:
        """Test case for list_all_system_opensearch_indexes_v1_search_admin_index_all_system_get

        List All System Indexes
        """
        pass

    def test_list_app_opensearch_indexes_v1_search_admin_index_app_indexes_get(self) -> None:
        """Test case for list_app_opensearch_indexes_v1_search_admin_index_app_indexes_get

        List Application Indexes
        """
        pass

    def test_trigger_doc_indexing_v1_search_admin_index_docs_post(self) -> None:
        """Test case for trigger_doc_indexing_v1_search_admin_index_docs_post

        Trigger Documentation Indexing
        """
        pass

    def test_update_index_configuration_v1_search_admin_index_index_name_settings_put(self) -> None:
        """Test case for update_index_configuration_v1_search_admin_index_index_name_settings_put

        Update Index Settings
        """
        pass


if __name__ == '__main__':
    unittest.main()
