# coding: utf-8

"""
    ValStorm API

    Build better business with ValStorm APIs

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from valstorm_api.models.start_task import StartTask

class TestStartTask(unittest.TestCase):
    """StartTask unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StartTask:
        """Test StartTask
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StartTask`
        """
        model = StartTask()
        if include_optional:
            return StartTask(
                task_name = '',
                task_args = { },
                task_kwargs = { }
            )
        else:
            return StartTask(
                task_name = '',
        )
        """

    def testStartTask(self):
        """Test StartTask"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
