# coding: utf-8

"""
    ValStorm API

    Build better business with ValStorm APIs

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from valstorm_api.api.auth_api import AuthApi


class TestAuthApi(unittest.TestCase):
    """AuthApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthApi()

    def tearDown(self) -> None:
        pass

    def test_initial_load_v1_auth_load_get(self) -> None:
        """Test case for initial_load_v1_auth_load_get

        Initial Load
        """
        pass

    def test_login_as_v1_auth_login_as_user_post(self) -> None:
        """Test case for login_as_v1_auth_login_as_user_post

        Login As
        """
        pass

    def test_logout_v1_auth_logout_post(self) -> None:
        """Test case for logout_v1_auth_logout_post

        Logout
        """
        pass

    def test_switch_org_v1_auth_switch_post(self) -> None:
        """Test case for switch_org_v1_auth_switch_post

        Switch Org
        """
        pass


if __name__ == '__main__':
    unittest.main()
