# coding: utf-8

"""
    ValStorm API

    Build better business with ValStorm APIs

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from valstorm_api.api.marketing_api import MarketingApi


class TestMarketingApi(unittest.TestCase):
    """MarketingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MarketingApi()

    def tearDown(self) -> None:
        pass

    def test_bulk_send_v1_marketing_campaign_bulk_send_post(self) -> None:
        """Test case for bulk_send_v1_marketing_campaign_bulk_send_post

        Bulk Send
        """
        pass

    def test_csv_to_json_v1_marketing_campaign_csv_to_json_post(self) -> None:
        """Test case for csv_to_json_v1_marketing_campaign_csv_to_json_post

        Csv To Json
        """
        pass


if __name__ == '__main__':
    unittest.main()
