# coding: utf-8

"""
    ValStorm API

    Build better business with ValStorm APIs

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from valstorm_api.models.email_message import EmailMessage

class TestEmailMessage(unittest.TestCase):
    """EmailMessage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EmailMessage:
        """Test EmailMessage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EmailMessage`
        """
        model = EmailMessage()
        if include_optional:
            return EmailMessage(
                subject = '',
                content = '',
                from_address = '',
                to_address = '',
                html_content = ''
            )
        else:
            return EmailMessage(
                subject = '',
                content = '',
                from_address = '',
                to_address = '',
        )
        """

    def testEmailMessage(self):
        """Test EmailMessage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
