# coding: utf-8

"""
    ValStorm API

    Build better business with ValStorm APIs

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from valstorm_api.api.tasks_api import TasksApi


class TestTasksApi(unittest.TestCase):
    """TasksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TasksApi()

    def tearDown(self) -> None:
        pass

    def test_check_availability_v1_tasks_availability_post(self) -> None:
        """Test case for check_availability_v1_tasks_availability_post

        Check Availability
        """
        pass

    def test_fix_convos_task_v1_tasks_fix_convos_post(self) -> None:
        """Test case for fix_convos_task_v1_tasks_fix_convos_post

        Fix Convos Task
        """
        pass

    def test_rebuild_schemas_route_v1_tasks_rebuild_schemas_post(self) -> None:
        """Test case for rebuild_schemas_route_v1_tasks_rebuild_schemas_post

        Rebuild Schemas Route
        """
        pass

    def test_start_function_v1_tasks_functions_post(self) -> None:
        """Test case for start_function_v1_tasks_functions_post

        Start Function
        """
        pass

    def test_start_task_v1_tasks_post(self) -> None:
        """Test case for start_task_v1_tasks_post

        Start Task
        """
        pass

    def test_system_alert_v1_tasks_system_alert_post(self) -> None:
        """Test case for system_alert_v1_tasks_system_alert_post

        System Alert
        """
        pass


if __name__ == '__main__':
    unittest.main()
