# coding: utf-8

"""
    ValStorm API

    Build better business with ValStorm APIs

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from valstorm_api.api.automation_api import AutomationApi


class TestAutomationApi(unittest.TestCase):
    """AutomationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AutomationApi()

    def tearDown(self) -> None:
        pass

    def test_resume_automation_route_v1_automation_resume_run_id_post(self) -> None:
        """Test case for resume_automation_route_v1_automation_resume_run_id_post

        Resume Automation Route
        """
        pass

    def test_run_automation_by_id_route_v1_automation_automation_id_post(self) -> None:
        """Test case for run_automation_by_id_route_v1_automation_automation_id_post

        Run Automation By Id Route
        """
        pass

    def test_run_automation_route_v1_automation_post(self) -> None:
        """Test case for run_automation_route_v1_automation_post

        Run Automation Route
        """
        pass

    def test_run_function_automation_route_v1_automation_function_post(self) -> None:
        """Test case for run_function_automation_route_v1_automation_function_post

        Run Function Automation Route
        """
        pass

    def test_run_partial_automation_route_v1_automation_run_partial_run_id_post(self) -> None:
        """Test case for run_partial_automation_route_v1_automation_run_partial_run_id_post

        Run Partial Automation Route
        """
        pass

    def test_run_public_automation_route_v1_public_automation_org_id_automation_id_post(self) -> None:
        """Test case for run_public_automation_route_v1_public_automation_org_id_automation_id_post

        Run Public Automation Route
        """
        pass


if __name__ == '__main__':
    unittest.main()
