# coding: utf-8

"""
    ValStorm API

    Build better business with ValStorm APIs

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from valstorm_api.api.twilio_conversation_webhooks_api import TwilioConversationWebhooksApi


class TestTwilioConversationWebhooksApi(unittest.TestCase):
    """TwilioConversationWebhooksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TwilioConversationWebhooksApi()

    def tearDown(self) -> None:
        pass

    def test_create_conversation_webhooks_v1_twilio_conversation_org_id_post_webhook_post(self) -> None:
        """Test case for create_conversation_webhooks_v1_twilio_conversation_org_id_post_webhook_post

        Create Conversation Webhooks
        """
        pass

    def test_get_conversation_webhooks_v1_twilio_conversation_webhooks_get(self) -> None:
        """Test case for get_conversation_webhooks_v1_twilio_conversation_webhooks_get

        Get Conversation Webhooks
        """
        pass

    def test_update_webhook_v1_twilio_conversation_webhooks_post(self) -> None:
        """Test case for update_webhook_v1_twilio_conversation_webhooks_post

        Update Webhook
        """
        pass


if __name__ == '__main__':
    unittest.main()
