# coding: utf-8

"""
    ValStorm API

    Build better business with ValStorm APIs

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from valstorm_api.api.query_api import QueryApi


class TestQueryApi(unittest.TestCase):
    """QueryApi unit test stubs"""

    def setUp(self) -> None:
        self.api = QueryApi()

    def tearDown(self) -> None:
        pass

    def test_mongo_query_route_v2_v1_query_mongo_post(self) -> None:
        """Test case for mongo_query_route_v2_v1_query_mongo_post

        Mongo Query Route V2
        """
        pass

    def test_sql_query_post_route_v1_query_post(self) -> None:
        """Test case for sql_query_post_route_v1_query_post

        Sql Query Post Route
        """
        pass

    def test_sql_query_route_v1_query_get(self) -> None:
        """Test case for sql_query_route_v1_query_get

        Sql Query Route
        """
        pass


if __name__ == '__main__':
    unittest.main()
