# coding: utf-8

"""
    ValStorm API

    Build better business with ValStorm APIs

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from valstorm_api.api.google_api import GoogleApi


class TestGoogleApi(unittest.TestCase):
    """GoogleApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GoogleApi()

    def tearDown(self) -> None:
        pass

    def test_calendar_sync_route_v1_google_calendar_sync_post(self) -> None:
        """Test case for calendar_sync_route_v1_google_calendar_sync_post

        Calendar Sync Route
        """
        pass

    def test_callback_google_v1_google_auth_callback_get(self) -> None:
        """Test case for callback_google_v1_google_auth_callback_get

        Callback Google
        """
        pass

    def test_create_drive_root_subscription_route_v1_google_create_drive_subscription_post(self) -> None:
        """Test case for create_drive_root_subscription_route_v1_google_create_drive_subscription_post

        Create Drive Root Subscription Route
        """
        pass

    def test_create_pubsub_subscription_route_v1_google_create_pubsub_subscription_post(self) -> None:
        """Test case for create_pubsub_subscription_route_v1_google_create_pubsub_subscription_post

        Create Pubsub Subscription Route
        """
        pass

    def test_delete_pubsub_subscription_route_v1_google_delete_pubsub_subscription_post(self) -> None:
        """Test case for delete_pubsub_subscription_route_v1_google_delete_pubsub_subscription_post

        Delete Pubsub Subscription Route
        """
        pass

    def test_drive_sync_route_v1_google_drive_sync_post(self) -> None:
        """Test case for drive_sync_route_v1_google_drive_sync_post

        Drive Sync Route
        """
        pass

    def test_get_calendar_list_route_v1_google_calendar_list_get(self) -> None:
        """Test case for get_calendar_list_route_v1_google_calendar_list_get

        Get Calendar List Route
        """
        pass

    def test_get_drive_file_content_route_v1_google_drive_file_content_file_id_get(self) -> None:
        """Test case for get_drive_file_content_route_v1_google_drive_file_content_file_id_get

        Get Drive File Content Route
        """
        pass

    def test_get_drive_file_list_route_v1_google_drive_files_list_get(self) -> None:
        """Test case for get_drive_file_list_route_v1_google_drive_files_list_get

        Get Drive File List Route
        """
        pass

    def test_get_drive_file_route_v1_google_drive_file_file_id_get(self) -> None:
        """Test case for get_drive_file_route_v1_google_drive_file_file_id_get

        Get Drive File Route
        """
        pass

    def test_get_drive_list_route_v1_google_drive_list_get(self) -> None:
        """Test case for get_drive_list_route_v1_google_drive_list_get

        Get Drive List Route
        """
        pass

    def test_get_email_history_route_v1_google_email_history_history_id_get(self) -> None:
        """Test case for get_email_history_route_v1_google_email_history_history_id_get

        Get Email History Route
        """
        pass

    def test_get_email_list_route_v1_google_email_list_get(self) -> None:
        """Test case for get_email_list_route_v1_google_email_list_get

        Get Email List Route
        """
        pass

    def test_get_email_route_v1_google_email_email_id_get(self) -> None:
        """Test case for get_email_route_v1_google_email_email_id_get

        Get Email Route
        """
        pass

    def test_get_email_thread_route_v1_google_email_thread_thread_id_get(self) -> None:
        """Test case for get_email_thread_route_v1_google_email_thread_thread_id_get

        Get Email Thread Route
        """
        pass

    def test_get_event_list_route_v1_google_events_list_get(self) -> None:
        """Test case for get_event_list_route_v1_google_events_list_get

        Get Event List Route
        """
        pass

    def test_get_event_route_v1_google_events_event_id_get(self) -> None:
        """Test case for get_event_route_v1_google_events_event_id_get

        Get Event Route
        """
        pass

    def test_get_google_doc_route_v1_google_doc_file_id_get(self) -> None:
        """Test case for get_google_doc_route_v1_google_doc_file_id_get

        Get Google Doc Route
        """
        pass

    def test_get_people_list_route_v1_google_people_list_get(self) -> None:
        """Test case for get_people_list_route_v1_google_people_list_get

        Get People List Route
        """
        pass

    def test_gmail_sync_route_v1_google_gmail_sync_post(self) -> None:
        """Test case for gmail_sync_route_v1_google_gmail_sync_post

        Gmail Sync Route
        """
        pass

    def test_google_calendar_pub_sub_v1_google_calendar_pub_sub_user_id_org_id_calendar_id_post(self) -> None:
        """Test case for google_calendar_pub_sub_v1_google_calendar_pub_sub_user_id_org_id_calendar_id_post

        Google Calendar Pub Sub
        """
        pass

    def test_google_drive_pub_sub_v1_google_drive_pub_sub_user_id_org_id_file_id_post(self) -> None:
        """Test case for google_drive_pub_sub_v1_google_drive_pub_sub_user_id_org_id_file_id_post

        Google Drive Pub Sub
        """
        pass

    def test_google_pub_sub_v1_google_pub_sub_org_id_post(self) -> None:
        """Test case for google_pub_sub_v1_google_pub_sub_org_id_post

        Google Pub Sub
        """
        pass

    def test_login_google_v1_google_auth_login_get(self) -> None:
        """Test case for login_google_v1_google_auth_login_get

        Login Google
        """
        pass

    def test_send_gmail_route_v1_google_gmail_send_post(self) -> None:
        """Test case for send_gmail_route_v1_google_gmail_send_post

        Send Gmail Route
        """
        pass

    def test_stop_gmail_route_v1_google_gmail_stop_post(self) -> None:
        """Test case for stop_gmail_route_v1_google_gmail_stop_post

        Stop Gmail Route
        """
        pass

    def test_watch_calendar_route_v1_google_calendar_watch_calendar_id_post(self) -> None:
        """Test case for watch_calendar_route_v1_google_calendar_watch_calendar_id_post

        Watch Calendar Route
        """
        pass

    def test_watch_drive_file_route_v1_google_drive_watch_file_id_post(self) -> None:
        """Test case for watch_drive_file_route_v1_google_drive_watch_file_id_post

        Watch Drive File Route
        """
        pass

    def test_watch_gmail_route_v1_google_gmail_watch_post(self) -> None:
        """Test case for watch_gmail_route_v1_google_gmail_watch_post

        Watch Gmail Route
        """
        pass


if __name__ == '__main__':
    unittest.main()
