# coding: utf-8

"""
    ValStorm API

    Build better business with ValStorm APIs

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class FieldCreateUpdateRequest(BaseModel):
    """
    FieldCreateUpdateRequest
    """ # noqa: E501
    object_id: StrictStr
    name: StrictStr
    api_name: StrictStr
    description: Optional[StrictStr] = None
    help_text: Optional[StrictStr] = None
    type: StrictStr
    format: Optional[StrictStr] = None
    required: StrictBool
    default: Optional[Any] = None
    sensitive: Optional[StrictBool] = False
    encrypted: Optional[StrictBool] = False
    app: StrictStr
    var_schema: Optional[StrictStr] = Field(default=None, alias="schema")
    values: Optional[List[Any]] = None
    global_: Optional[StrictBool] = False
    global_list_name: Optional[StrictStr] = None
    object: Optional[StrictStr] = None
    restricted: Optional[StrictBool] = False
    pii: Optional[StrictBool] = False
    phi: Optional[StrictBool] = False
    plural_name: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["object_id", "name", "api_name", "description", "help_text", "type", "format", "required", "default", "sensitive", "encrypted", "app", "schema", "values", "global_", "global_list_name", "object", "restricted", "pii", "phi", "plural_name"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FieldCreateUpdateRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of default
        if self.default:
            _dict['default'] = self.default.to_dict()
        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if help_text (nullable) is None
        # and model_fields_set contains the field
        if self.help_text is None and "help_text" in self.model_fields_set:
            _dict['help_text'] = None

        # set to None if format (nullable) is None
        # and model_fields_set contains the field
        if self.format is None and "format" in self.model_fields_set:
            _dict['format'] = None

        # set to None if default (nullable) is None
        # and model_fields_set contains the field
        if self.default is None and "default" in self.model_fields_set:
            _dict['default'] = None

        # set to None if var_schema (nullable) is None
        # and model_fields_set contains the field
        if self.var_schema is None and "var_schema" in self.model_fields_set:
            _dict['schema'] = None

        # set to None if values (nullable) is None
        # and model_fields_set contains the field
        if self.values is None and "values" in self.model_fields_set:
            _dict['values'] = None

        # set to None if global_list_name (nullable) is None
        # and model_fields_set contains the field
        if self.global_list_name is None and "global_list_name" in self.model_fields_set:
            _dict['global_list_name'] = None

        # set to None if object (nullable) is None
        # and model_fields_set contains the field
        if self.object is None and "object" in self.model_fields_set:
            _dict['object'] = None

        # set to None if plural_name (nullable) is None
        # and model_fields_set contains the field
        if self.plural_name is None and "plural_name" in self.model_fields_set:
            _dict['plural_name'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FieldCreateUpdateRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "object_id": obj.get("object_id"),
            "name": obj.get("name"),
            "api_name": obj.get("api_name"),
            "description": obj.get("description"),
            "help_text": obj.get("help_text"),
            "type": obj.get("type"),
            "format": obj.get("format"),
            "required": obj.get("required"),
            "default": AnyOf.from_dict(obj["default"]) if obj.get("default") is not None else None,
            "sensitive": obj.get("sensitive") if obj.get("sensitive") is not None else False,
            "encrypted": obj.get("encrypted") if obj.get("encrypted") is not None else False,
            "app": obj.get("app"),
            "schema": obj.get("schema"),
            "values": obj.get("values"),
            "global_": obj.get("global_") if obj.get("global_") is not None else False,
            "global_list_name": obj.get("global_list_name"),
            "object": obj.get("object"),
            "restricted": obj.get("restricted") if obj.get("restricted") is not None else False,
            "pii": obj.get("pii") if obj.get("pii") is not None else False,
            "phi": obj.get("phi") if obj.get("phi") is not None else False,
            "plural_name": obj.get("plural_name")
        })
        return _obj


