# coding: utf-8

"""
    ValStorm API

    Build better business with ValStorm APIs

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from valstorm_api.models.axis_field import AxisField
from valstorm_api.models.model_field import ModelField
from typing import Optional, Set
from typing_extensions import Self

class FrontendAnalyticsRequest(BaseModel):
    """
    FrontendAnalyticsRequest
    """ # noqa: E501
    query: StrictStr
    chart_type: StrictStr = Field(alias="chartType")
    var_field: Optional[List[ModelField]] = Field(default=None, alias="field")
    x: Optional[List[AxisField]] = None
    y: Optional[List[AxisField]] = None
    aggregate: Optional[StrictStr] = None
    summarize_by: Optional[StrictStr] = Field(default=None, alias="summarizeBy")
    group_by_date_time: Optional[StrictStr] = Field(default=None, alias="groupByDateTime")
    dashboard_id: Optional[StrictStr] = None
    component_id: Optional[StrictStr] = None
    object_id: Optional[StrictStr] = None
    item: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["query", "chartType", "field", "x", "y", "aggregate", "summarizeBy", "groupByDateTime", "dashboard_id", "component_id", "object_id", "item"]

    @field_validator('group_by_date_time')
    def group_by_date_time_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Minute', 'Hour', 'Day', 'Week', 'Month', 'Quarter', 'Year']):
            raise ValueError("must be one of enum values ('Minute', 'Hour', 'Day', 'Week', 'Month', 'Quarter', 'Year')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FrontendAnalyticsRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in var_field (list)
        _items = []
        if self.var_field:
            for _item_var_field in self.var_field:
                if _item_var_field:
                    _items.append(_item_var_field.to_dict())
            _dict['field'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in x (list)
        _items = []
        if self.x:
            for _item_x in self.x:
                if _item_x:
                    _items.append(_item_x.to_dict())
            _dict['x'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in y (list)
        _items = []
        if self.y:
            for _item_y in self.y:
                if _item_y:
                    _items.append(_item_y.to_dict())
            _dict['y'] = _items
        # set to None if var_field (nullable) is None
        # and model_fields_set contains the field
        if self.var_field is None and "var_field" in self.model_fields_set:
            _dict['field'] = None

        # set to None if x (nullable) is None
        # and model_fields_set contains the field
        if self.x is None and "x" in self.model_fields_set:
            _dict['x'] = None

        # set to None if y (nullable) is None
        # and model_fields_set contains the field
        if self.y is None and "y" in self.model_fields_set:
            _dict['y'] = None

        # set to None if aggregate (nullable) is None
        # and model_fields_set contains the field
        if self.aggregate is None and "aggregate" in self.model_fields_set:
            _dict['aggregate'] = None

        # set to None if summarize_by (nullable) is None
        # and model_fields_set contains the field
        if self.summarize_by is None and "summarize_by" in self.model_fields_set:
            _dict['summarizeBy'] = None

        # set to None if group_by_date_time (nullable) is None
        # and model_fields_set contains the field
        if self.group_by_date_time is None and "group_by_date_time" in self.model_fields_set:
            _dict['groupByDateTime'] = None

        # set to None if dashboard_id (nullable) is None
        # and model_fields_set contains the field
        if self.dashboard_id is None and "dashboard_id" in self.model_fields_set:
            _dict['dashboard_id'] = None

        # set to None if component_id (nullable) is None
        # and model_fields_set contains the field
        if self.component_id is None and "component_id" in self.model_fields_set:
            _dict['component_id'] = None

        # set to None if object_id (nullable) is None
        # and model_fields_set contains the field
        if self.object_id is None and "object_id" in self.model_fields_set:
            _dict['object_id'] = None

        # set to None if item (nullable) is None
        # and model_fields_set contains the field
        if self.item is None and "item" in self.model_fields_set:
            _dict['item'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FrontendAnalyticsRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "query": obj.get("query"),
            "chartType": obj.get("chartType"),
            "field": [ModelField.from_dict(_item) for _item in obj["field"]] if obj.get("field") is not None else None,
            "x": [AxisField.from_dict(_item) for _item in obj["x"]] if obj.get("x") is not None else None,
            "y": [AxisField.from_dict(_item) for _item in obj["y"]] if obj.get("y") is not None else None,
            "aggregate": obj.get("aggregate"),
            "summarizeBy": obj.get("summarizeBy"),
            "groupByDateTime": obj.get("groupByDateTime"),
            "dashboard_id": obj.get("dashboard_id"),
            "component_id": obj.get("component_id"),
            "object_id": obj.get("object_id"),
            "item": obj.get("item")
        })
        return _obj


