# coding: utf-8

"""
    ValStorm API

    Build better business with ValStorm APIs

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class PhoneAddressType(str, Enum):
    """
    PhoneAddressType
    """

    """
    allowed enum values
    """
    SMS = 'sms'
    WHATSAPP = 'whatsapp'
    MESSENGER = 'messenger'
    GBM = 'gbm'
    EMAIL = 'email'
    RCS = 'rcs'
    APPLE = 'apple'
    CHAT = 'chat'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PhoneAddressType from a JSON string"""
        return cls(json.loads(json_str))


