# coding: utf-8

"""
    ValStorm API

    Build better business with ValStorm APIs

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from valstorm_api.models.send_grid_enable import SendGridEnable
from valstorm_api.models.send_grid_footer_settings import SendGridFooterSettings
from typing import Optional, Set
from typing_extensions import Self

class SendGridMailSettings(BaseModel):
    """
    SendGridMailSettings
    """ # noqa: E501
    footer_settings: Optional[SendGridFooterSettings] = None
    sandbox_mode: Optional[SendGridEnable] = None
    bypass_list_management: Optional[SendGridEnable] = None
    bypass_spam_management: Optional[SendGridEnable] = None
    bypass_bounce_management: Optional[SendGridEnable] = None
    bypass_unsubscribe_management: Optional[SendGridEnable] = None
    __properties: ClassVar[List[str]] = ["footer_settings", "sandbox_mode", "bypass_list_management", "bypass_spam_management", "bypass_bounce_management", "bypass_unsubscribe_management"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SendGridMailSettings from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of footer_settings
        if self.footer_settings:
            _dict['footer_settings'] = self.footer_settings.to_dict()
        # override the default output from pydantic by calling `to_dict()` of sandbox_mode
        if self.sandbox_mode:
            _dict['sandbox_mode'] = self.sandbox_mode.to_dict()
        # override the default output from pydantic by calling `to_dict()` of bypass_list_management
        if self.bypass_list_management:
            _dict['bypass_list_management'] = self.bypass_list_management.to_dict()
        # override the default output from pydantic by calling `to_dict()` of bypass_spam_management
        if self.bypass_spam_management:
            _dict['bypass_spam_management'] = self.bypass_spam_management.to_dict()
        # override the default output from pydantic by calling `to_dict()` of bypass_bounce_management
        if self.bypass_bounce_management:
            _dict['bypass_bounce_management'] = self.bypass_bounce_management.to_dict()
        # override the default output from pydantic by calling `to_dict()` of bypass_unsubscribe_management
        if self.bypass_unsubscribe_management:
            _dict['bypass_unsubscribe_management'] = self.bypass_unsubscribe_management.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SendGridMailSettings from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "footer_settings": SendGridFooterSettings.from_dict(obj["footer_settings"]) if obj.get("footer_settings") is not None else None,
            "sandbox_mode": SendGridEnable.from_dict(obj["sandbox_mode"]) if obj.get("sandbox_mode") is not None else None,
            "bypass_list_management": SendGridEnable.from_dict(obj["bypass_list_management"]) if obj.get("bypass_list_management") is not None else None,
            "bypass_spam_management": SendGridEnable.from_dict(obj["bypass_spam_management"]) if obj.get("bypass_spam_management") is not None else None,
            "bypass_bounce_management": SendGridEnable.from_dict(obj["bypass_bounce_management"]) if obj.get("bypass_bounce_management") is not None else None,
            "bypass_unsubscribe_management": SendGridEnable.from_dict(obj["bypass_unsubscribe_management"]) if obj.get("bypass_unsubscribe_management") is not None else None
        })
        return _obj


