# coding: utf-8

"""
    ValStorm API

    Build better business with ValStorm APIs

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from valstorm_api.models.call_status import CallStatus
from typing import Optional, Set
from typing_extensions import Self

class StatusStatusRoutesAvailable(BaseModel):
    """
    StatusStatusRoutesAvailable
    """ # noqa: E501
    call_status: Optional[CallStatus] = None
    reset: Optional[StrictBool] = False
    user_id: Optional[StrictStr] = None
    available_for_mobile_calls: Optional[StrictBool] = True
    available_for_web_calls: Optional[StrictBool] = True
    allow_mobile_calls: Optional[StrictBool] = True
    allow_web_calls: Optional[StrictBool] = True
    has_mobile_app: Optional[StrictBool] = True
    __properties: ClassVar[List[str]] = ["call_status", "reset", "user_id", "available_for_mobile_calls", "available_for_web_calls", "allow_mobile_calls", "allow_web_calls", "has_mobile_app"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StatusStatusRoutesAvailable from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if user_id (nullable) is None
        # and model_fields_set contains the field
        if self.user_id is None and "user_id" in self.model_fields_set:
            _dict['user_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StatusStatusRoutesAvailable from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "call_status": obj.get("call_status"),
            "reset": obj.get("reset") if obj.get("reset") is not None else False,
            "user_id": obj.get("user_id"),
            "available_for_mobile_calls": obj.get("available_for_mobile_calls") if obj.get("available_for_mobile_calls") is not None else True,
            "available_for_web_calls": obj.get("available_for_web_calls") if obj.get("available_for_web_calls") is not None else True,
            "allow_mobile_calls": obj.get("allow_mobile_calls") if obj.get("allow_mobile_calls") is not None else True,
            "allow_web_calls": obj.get("allow_web_calls") if obj.get("allow_web_calls") is not None else True,
            "has_mobile_app": obj.get("has_mobile_app") if obj.get("has_mobile_app") is not None else True
        })
        return _obj


