# coding: utf-8

"""
    ValStorm API

    Build better business with ValStorm APIs

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from valstorm_api.models.from_number import FromNumber
from valstorm_api.models.merge_data import MergeData
from valstorm_api.models.template_id1 import TemplateId1
from typing import Optional, Set
from typing_extensions import Self

class TwilioSMS(BaseModel):
    """
    TwilioSMS
    """ # noqa: E501
    from_number: Optional[FromNumber] = None
    to: Optional[StrictStr] = None
    body: Optional[StrictStr] = None
    template_id: Optional[TemplateId1] = None
    merge_data: Optional[MergeData] = None
    conversation_sid: Optional[StrictStr] = None
    media_sid: Optional[StrictStr] = None
    media: Optional[List[Any]] = None
    automated: Optional[StrictBool] = True
    use_conversations: Optional[StrictBool] = True
    run_date_time: Optional[datetime] = None
    contact: Optional[Dict[str, Any]] = None
    phone: Optional[Dict[str, Any]] = None
    conversation: Optional[Dict[str, Any]] = None
    participant: Optional[Dict[str, Any]] = None
    scheduled_item_id: Optional[StrictStr] = None
    campaign_id: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["from_number", "to", "body", "template_id", "merge_data", "conversation_sid", "media_sid", "media", "automated", "use_conversations", "run_date_time", "contact", "phone", "conversation", "participant", "scheduled_item_id", "campaign_id"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TwilioSMS from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of from_number
        if self.from_number:
            _dict['from_number'] = self.from_number.to_dict()
        # override the default output from pydantic by calling `to_dict()` of template_id
        if self.template_id:
            _dict['template_id'] = self.template_id.to_dict()
        # override the default output from pydantic by calling `to_dict()` of merge_data
        if self.merge_data:
            _dict['merge_data'] = self.merge_data.to_dict()
        # set to None if from_number (nullable) is None
        # and model_fields_set contains the field
        if self.from_number is None and "from_number" in self.model_fields_set:
            _dict['from_number'] = None

        # set to None if to (nullable) is None
        # and model_fields_set contains the field
        if self.to is None and "to" in self.model_fields_set:
            _dict['to'] = None

        # set to None if body (nullable) is None
        # and model_fields_set contains the field
        if self.body is None and "body" in self.model_fields_set:
            _dict['body'] = None

        # set to None if template_id (nullable) is None
        # and model_fields_set contains the field
        if self.template_id is None and "template_id" in self.model_fields_set:
            _dict['template_id'] = None

        # set to None if merge_data (nullable) is None
        # and model_fields_set contains the field
        if self.merge_data is None and "merge_data" in self.model_fields_set:
            _dict['merge_data'] = None

        # set to None if conversation_sid (nullable) is None
        # and model_fields_set contains the field
        if self.conversation_sid is None and "conversation_sid" in self.model_fields_set:
            _dict['conversation_sid'] = None

        # set to None if media_sid (nullable) is None
        # and model_fields_set contains the field
        if self.media_sid is None and "media_sid" in self.model_fields_set:
            _dict['media_sid'] = None

        # set to None if media (nullable) is None
        # and model_fields_set contains the field
        if self.media is None and "media" in self.model_fields_set:
            _dict['media'] = None

        # set to None if run_date_time (nullable) is None
        # and model_fields_set contains the field
        if self.run_date_time is None and "run_date_time" in self.model_fields_set:
            _dict['run_date_time'] = None

        # set to None if contact (nullable) is None
        # and model_fields_set contains the field
        if self.contact is None and "contact" in self.model_fields_set:
            _dict['contact'] = None

        # set to None if phone (nullable) is None
        # and model_fields_set contains the field
        if self.phone is None and "phone" in self.model_fields_set:
            _dict['phone'] = None

        # set to None if conversation (nullable) is None
        # and model_fields_set contains the field
        if self.conversation is None and "conversation" in self.model_fields_set:
            _dict['conversation'] = None

        # set to None if participant (nullable) is None
        # and model_fields_set contains the field
        if self.participant is None and "participant" in self.model_fields_set:
            _dict['participant'] = None

        # set to None if scheduled_item_id (nullable) is None
        # and model_fields_set contains the field
        if self.scheduled_item_id is None and "scheduled_item_id" in self.model_fields_set:
            _dict['scheduled_item_id'] = None

        # set to None if campaign_id (nullable) is None
        # and model_fields_set contains the field
        if self.campaign_id is None and "campaign_id" in self.model_fields_set:
            _dict['campaign_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TwilioSMS from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "from_number": FromNumber.from_dict(obj["from_number"]) if obj.get("from_number") is not None else None,
            "to": obj.get("to"),
            "body": obj.get("body"),
            "template_id": TemplateId1.from_dict(obj["template_id"]) if obj.get("template_id") is not None else None,
            "merge_data": MergeData.from_dict(obj["merge_data"]) if obj.get("merge_data") is not None else None,
            "conversation_sid": obj.get("conversation_sid"),
            "media_sid": obj.get("media_sid"),
            "media": obj.get("media"),
            "automated": obj.get("automated") if obj.get("automated") is not None else True,
            "use_conversations": obj.get("use_conversations") if obj.get("use_conversations") is not None else True,
            "run_date_time": obj.get("run_date_time"),
            "contact": obj.get("contact"),
            "phone": obj.get("phone"),
            "conversation": obj.get("conversation"),
            "participant": obj.get("participant"),
            "scheduled_item_id": obj.get("scheduled_item_id"),
            "campaign_id": obj.get("campaign_id")
        })
        return _obj


